{
 "title": "Risk Factors",
 "tags": [
  "crypto",
  "risk-factors"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "BTC",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_risk_factor{coin=\"BTC\"}",
     "legendFormat": "BTC"
    }
   ]
  },
  {
   "title": "ETH",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_risk_factor{coin=\"ETH\"}",
     "legendFormat": "ETH"
    }
   ]
  },
  {
   "title": "SOL",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_risk_factor{coin=\"SOL\"}",
     "legendFormat": "SOL"
    }
   ]
  },
  {
   "title": "XRP",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_risk_factor{coin=\"XRP\"}",
     "legendFormat": "XRP"
    }
   ]
  },
  {
   "title": "BNB",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_risk_factor{coin=\"BNB\"}",
     "legendFormat": "BNB"
    }
   ]
  },
  {
   "title": "XMR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_risk_factor{coin=\"XMR\"}",
     "legendFormat": "XMR"
    }
   ]
  },
  {
   "title": "TRX",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_risk_factor{coin=\"TRX\"}",
     "legendFormat": "TRX"
    }
   ]
  },
  {
   "title": "ADA",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_risk_factor{coin=\"ADA\"}",
     "legendFormat": "ADA"
    }
   ]
  },
  {
   "title": "LTC",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_risk_factor{coin=\"LTC\"}",
     "legendFormat": "LTC"
    }
   ]
  },
  {
   "title": "LINK",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_risk_factor{coin=\"LINK\"}",
     "legendFormat": "LINK"
    }
   ]
  },
  {
   "title": "XLM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_risk_factor{coin=\"XLM\"}",
     "legendFormat": "XLM"
    }
   ]
  },
  {
   "title": "SKY",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_risk_factor{coin=\"SKY\"}",
     "legendFormat": "SKY"
    }
   ]
  },
  {
   "title": "TOTAL",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_risk_factor{coin=\"TOTAL\"}",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "BTC Price to Risk Factor",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "crypto_risk_factor_table{coin=\"BTC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETH Price to Risk Factor",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "crypto_risk_factor_table{coin=\"ETH\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BTC Risk Factor Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "crypto_risk_factor{coin=\"BTC\"}",
     "legendFormat": "BTC Risk"
    }
   ]
  }
 ]
}